grid_map_topic: /mobile_map

grid_map_visualizations:

  - name: elevation
    type: occupancy_grid
    params:
     layer: elevation
     data_min: 0.0
     data_max: 5.0

  - name: person_number
    type: occupancy_grid
    params:
     layer: person_number
     data_min: 0.0
     data_max: 5.0

  - name: person_posture
    type: occupancy_grid
    params:
     layer: person_posture
     data_min: 0.0
     data_max: 5.0

  - name: person_flow_x
    type: occupancy_grid
    params:
     layer: person_flow_x
     data_min: -5.0
     data_max: 5.0

  - name: person_flow_y
    type: occupancy_grid
    params:
     layer: person_flow_y
     data_min: -5.0
     data_max: 5.0
     
     
