grid_map_topic: /osr_map

grid_map_visualizations:

  - name: object_update_og
    type: occupancy_grid
    params:
     layer: object_update
     data_min: 0.0
     data_max: 1.0


  - name: elevation_update_og
    type: occupancy_grid
    params:
     layer: elevation_update
     data_min: 0.0
     data_max: 1.0

  - name: thermal_update_og
    type: occupancy_grid
    params:
     layer: thermal_update
     data_min: 0.0
     data_max: 1.0

  - name: elevation_pc
    type: point_cloud
    params:
     layer: elevation
       

  - name: elevation_og
    type: occupancy_grid
    params:
     layer: elevation
     data_min: 0.0
     data_max: 5.0

  - name: person_number_pc
    type: point_cloud
    params:
     layer: person_number

  - name: person_number_og
    type: occupancy_grid
    params:
     layer: person_number
     data_min: 0.0
     data_max: 3.0

  - name: car_number_pc
    type: point_cloud
    params:
     layer: car_number

  - name: car_number_og
    type: occupancy_grid
    params:
     layer: car_number
     data_min: 0.0
     data_max: 3.0

  - name: person_flow_x_og
    type: occupancy_grid
    params:
     layer: person_flow_x
     data_min: -1.5
     data_max: 1.5

  - name: person_flow_y_og
    type: occupancy_grid
    params:
     layer: person_flow_y
     data_min: -1.5
     data_max: 1.5

  - name: thermal_pc
    type: point_cloud
    params:
     layer: thermal
       
  - name: thermal_og
    type: occupancy_grid
    params:
     layer: thermal
     data_min: 0.0
     data_max: 100.0

     
